name: Leanote Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

env:
  BASE_IMAGE: alpine
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME: leanote

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: run
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: library/${{ env.BASE_IMAGE }}:latest
          image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.BASE_IMAGE }}
        continue-on-error: true
        if: github.event_name == 'schedule'
      - name: Check on result
        id: check
        run: |
          if [[ ${{ steps.run.outcome }} == 'success' ]]; then
            echo "needs-updating=${{ steps.run.outputs.needs-updating }}" >> $GITHUB_OUTPUT
          else
            echo "needs-updating=true" >> $GITHUB_OUTPUT
          fi
        if: github.event_name == 'schedule'

  build:
    needs: check
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'schedule' ||
      needs.check.outputs.needs-updating == 'true'

    strategy:
      matrix:
        version: ["2.5", "2.6.1"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Prepare
        id: prepare
        run: |
          TAGS="${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }},${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ env.BASE_IMAGE }}"
          if [[ ${{ matrix.version }} == '2.6.1' ]]; then
            TAGS+=",${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.BASE_IMAGE }},${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"
          fi
          echo "build_args=LEANOTE_VERSION=${{ matrix.version }}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json
